print('Hello, World!!')
print('친구야~ 안녕~~.')
print('선배님 안녕하세요.')
print('교수님 안녕하세요.')

print(3 + 5)
print(17 * 234)
print(30 * 4 / 5)

print('*   *    **    ****    ****    *   *')
print('*   *   *  *   *   *   *   *   *   *')
print('*****  *    *  ****    ****     * * ')
print('*   *  ******  *   *   *   *     *  ')
print('*   *  *    *  *    *  *    *    *  ')

print('            +---+')
print('            |   |')
print('        +---+---+')
print('        |   |   |')
print('    +---+---+---+')
print('    |   |   |   |')
print('+---+---+---+---+')
print('|   |   |   |   |')
print('+---+---+---+---+')

print('  /////  ')
print(' | 0 0 | ')
print('(|  ^  |)')
print(' | [_] | ')
print('  -----  ')

print('  /\_/\     -----   ')
print(' ( '"' '"' )  / Hello \ ')
print(' (  -  ) <  Junior |')
print('  | | |   \ Coder!/ ')
print(' (__|__)    -----   ')

print("  /\_/\     -----    ")
print(" ( ' ' )  / Hello \  ")
print(" (  -  ) <  Junior | ")
print("  | | |   \ Coder!/  ")
print(" (__|__)    -----    ")